### ISSUE TITLE
Confirmation codes from GMail are not parsed from Japanese email accounts

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1180]
Can see the log files by searching for "fiqq900szw8p"

**Comment by jacksonh** [comment]
Sadly it looks like there isn't a header with this value, but maybe the subject always matches this pattern:  `(#[0-9]{9})`

**Comment by sywhb** [comment]
This might be because we only treat the email as a confirmation email if `from` is 'Gmail Team <forwarding-noreply@google.com>' but this is from 'SWG チーム <forwarding-noreply@google.com>'

I will update the regex of `from` to match `forwarding-noreply@google.com`

**Comment by sywhb** [comment]
I should maybe test both `from` and `subject` and the confirmation code is not necessarily 9 digits so I probably will use this pattern `/\(#\d+\)/`

**Comment by sywhb** [comment]
Google Japan email team also uses unicode parentheses in email subject so updated the regex to match that

**Comment by sywhb** [comment]
`（#745359589）SWG の転送の確認 - miyanohara@nbi.academy からメールを受信`

**Comment by sywhb** [comment]
Created a PR to fix this: https://github.com/omnivore-app/omnivore/pull/1182#issuecomment-1241593614

**Comment by sywhb** [comment]
Fixed by #1182 
<img width="749" alt="Screenshot 2022-09-12 at 11 21 12 AM" src="https://user-images.githubusercontent.com/12963965/189567983-20fb76d5-3526-460f-90a7-cb06bbeb10ac.png">
<img width="912" alt="Screenshot 2022-09-12 at 11 21 37 AM" src="https://user-images.githubusercontent.com/12963965/189568015-a947333e-6baa-47bf-b584-da1145b4be76.png">
