### ISSUE TITLE
The Guardian article body is not saved

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1401]
I tried saving this article both from the Firefox extension and by adding the link straight into Omnivore. I get the same result:

![Screenshot 2022-11-09 at 5 58 32 PM](https://user-images.githubusercontent.com/42862428/200893261-b0011181-08e1-4d04-840d-3325adcaa1f0.jpg)

Only the title is saved.

**Comment by sywhb** [comment]
Hey @xplosionmind, thanks for reporting.

This seems to be fixed in the previous commit and I could not replicate it now.
<img width="978" alt="Screenshot 2022-12-01 at 2 45 33 PM" src="https://user-images.githubusercontent.com/12963965/204984234-03f865df-c239-42ca-b9b2-8a2281686985.png">

I'd really appreciate it if you could verify it on your end.
Test page in #1490

**Comment by xplosionmind** [comment]
> This seems to be fixed in the previous commit

Yes, it is! Thanks a lot.
