### ISSUE TITLE
Labels can not have chinese characters

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1707]
Reported on discord, can't create a label on iOS with Chinese characters

**Comment by sixten** [comment]
Was this fixed by #1751?

At any rate, I was able to paste some Chinese text into the label creation screen on iOS, select that label for one of the default articles, and verify that the label also appears on the web:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/7528/219820880-f04270a4-bfa0-4824-bb65-3097678e85a2.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/7528/219820907-4babe63e-c7bd-41f7-904c-ba2832fcbee3.png">

**Comment by jacksonh** [comment]
Hello, sorry I thought I followed up on this. This issue was fixed. Previously we were specifying the keyboard which preventing switching to a Chinese keyboard on entry
