### ISSUE TITLE
Remove `\n` from author names

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1892]
https://discord.com/channels/844965259462311966/942463305107259432/1083384928319844452

It looks like the author name from this file has `\n` in it after parsing, which breaks the logseg plugin. 

https://www.digitallawjournal.org/jour/article/view/5

**Comment by sywhb** [comment]
Fixed in #1962 

<img width="768" alt="Screenshot 2023-03-30 at 9 58 57 PM" src="https://user-images.githubusercontent.com/12963965/228860788-cf4b51c2-d29e-45a3-b92f-9959ea10c32a.png">

<img width="264" alt="Screenshot 2023-03-30 at 9 58 44 PM" src="https://user-images.githubusercontent.com/12963965/228860810-6636b99c-4b11-44ca-87fa-8ea570d0e7ec.png">
