### ISSUE TITLE
e-Ink Display Support

### ISSUE THREAD

**Issue by pedersen** [omnivore-app/omnivore#1956]
Would it be possible to update the Android app to better support e-ink displays? In particular, the Supernote comes to mind as I'm planning on purchasing it. Having it available in the Supernote app store would be even better, but I'll settle for sideloading at this point. Just so long as color palettes are possible to make it so that highlights are visible as highlights, I can add notes, and in general keep everything sync'ed up.

**Comment by jacksonh** [comment]
Hey @pedersen thank you for opening this ticket. I've been trying to find some e-ink devices to test this out with.

**Comment by pedersen** [comment]
Once I get it (currently saving up for it, and taking time to evaluate which one I want), I'd like to help out on the android side at the least. So, if you wanna wait until then, I'll jump in. If not, I won't complain either :)

**Comment by jacksonh** [comment]
@pedersen awesome good to hear. Yeah that model is out of my price range but I've heard there are some low end ones that function well enough for testing.

**Comment by rominf** [comment]
![IMG_20231126_104544_HDR.jpg](https://github.com/omnivore-app/omnivore/assets/3449635/566f6db7-839e-4b45-9416-28f5af4c6990)

Omnivore web app running with a light theme allows me to comfortably read most articles on e-ink display, connected to laptop and configured to black and white mode. This is great!

There is a small issue though: in the article list page the selected article is not visible, because it is highlighted with light gray fill which is rounded by the e-ink display to white. You can observe it by looking at the photo of the display, attached to the comment. I have checked that the first article in the list is indeed selected by moving the browser window to the LCD screen.

I understand that some users got used to the light theme and probably don't want any changes. My proposal would be to add an e-ink theme in addition to two existing themes, which would have just two colors for everything. In that case, the current article can be highlighted using black border.

PS: please feel free to move this comment to a separate issue - I was unsure whether to create a new issue for this comment or to use the existing one.
