### ISSUE TITLE
🐛 BUG: Obsidian Omnivore plugin does not create notes

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [omnivore-app/omnivore#2468]
When I try to sync the tutorial articles I get

![image](https://github.com/omnivore-app/omnivore/assets/86342787/74bc1b9d-5db7-45f6-95d2-b8eae42b61ab)

but nothing is created in obsidian. I have checked sync all articles. and i have an api key

**Comment by sschneider-ihre-pvs** [comment]
It seems that, if there has not been any changes, metadata or content they will not sync

**Comment by jacksonh** [comment]
@sschneider-ihre-pvs do you mean you add a note to an article that has already been synced, and then attempt to re-sync and the note is not pulled in?

**Comment by sschneider-ihre-pvs** [comment]
more like, a brand new account where only the tutorials are there and I cannot sync that, or if I add an article with the browser extension without changing anything it also seems to be ignored, as soon as I touch something the obsidian plugin is able to pull them in.

**Comment by aaachen** [comment]
I tested this issue and noticed the same. 
When I looked into further the issue reported is a result of the command behavior and default filter setting. There's no actual bug in Omnivore itself.

The plugin's two commands:
- Sync - sync any changes/delta from "Last Sync" date (i.e. when you run the Sync command)
- Resync - sync articles regardless "Last Sync" date (i.e. it clears the date and runs Sync) 

Filter: The condition to filter the result. The default is "import just Highlights"

The articles returned is the result pulled by Sync (or Resync), filtered down by the Filter.

This is my following sequence (and likely what OP did):
1. Run Sync (wanting to pull all my articles)
- Because it's a new account, nothing is highlighted/pulled
2. Run Sync/Resync again, same thing as 1.
3. Noticed the Filter in the setting, change to "import All my Articles"
4. Run Sync again
- **("Bug")** Because the behavior of Sync, only delta are being pulled in

If I do "Resync" after changing the filter condition, the plugin works correctly in pulling everything I need

**Comment by aaachen** [comment]
Admittedly this would seem like a bug on UX without any code insight, maybe we can
- Clarify the commands a bit? 
- Do a code change that if "Filter" is changed, we clear the last sync date? I think this makes sense UX wise

I'm also not sure what's the benefit of exposing the last sync field to user. It's more like an timestamp for internal use type of thing

**Comment by sywhb** [comment]
yeah, this is affecting more users and thanks guys for the clear description.

agree with @aaachen's both idea and i will work on them.

besides that, do you guys think we should default sync all items instead of just highlights? cc @jacksonh @sschneider-ihre-pvs

**Comment by aaachen** [comment]
Here's PR:
https://github.com/omnivore-app/obsidian-omnivore/pull/168

@sywhb I can help take this if you haven't got a chance yet to work on

**Comment by johnnynalley** [comment]
I believe I am experiencing this same issues. I've synced, resynced, and nothing populated the Omnivore folder. All of my settings are default, including the filter, so the full article should be saved. I added a few highlights and notes and those did not move over either. I have removed the plugin, created a new API key, and reinstalled the plugin using my new API key, and same result. I am on iOS 17.3.
