### ISSUE TITLE
Github Issues are not rendered correctly via RSS or browser extension

### ISSUE THREAD

**Issue by lily-mara** [omnivore-app/omnivore#2910]
I am subscribed to an RSS feed of a project's Github issues via rsshub ([feed](https://rsshub.app/github/issue/meixger/hackernews-daily)). I expect Omnivore to show me the contents of the issue in the app. Instead, I see what looks like an unstyled version of the header & footer.

![2023-10-11 15 04 55 omnivore app e5f0610d8c0a](https://github.com/omnivore-app/omnivore/assets/6109875/0d8bed3b-443a-46ef-a43e-5975dbeb919e)

I also tried saving the page to Omnivore via the browser extension, and found different but also incorrect rendering in the app.

![2023-10-11 15 05 26 omnivore app e5b7f6975fee](https://github.com/omnivore-app/omnivore/assets/6109875/e4519b0d-e1ab-4851-85c0-25bb91f34a33)

It's notable that the "description" of the items in the RSS feed contain exactly the information that I'm expecting to show up in Omnivore, but that isn't what I'm seeing in the app.

<img width="1374" alt=" 2023-10-11 at 15 06 22" src="https://github.com/omnivore-app/omnivore/assets/6109875/17382d3b-f3ac-4aa9-a9bc-7d89e5588c3b">

I also reported this via the in-app "report issues with this page" link, but I'm not sure where those reports are ending up

**Comment by jacksonh** [comment]
Hey first off regarding the reports we anonymize them and look at them, but because we strip user info we can't reply. We do this just in case someone accidentally reported something private. 

Right now with RSS we mostly ignore the descriptions and fetch the pages, but we are going to change that behavior soon. But the big issue is pages like this are just not fetched/parsed properly:

https://github.com/meixger/hackernews-daily/issues/407

I think what we need to do it get the first `class="edit-comment-hide"` element and treat that as the article (we can probably debate what a GitHub issue should even look like in a reader, but getting the top issue data is the most important bit.

We have a special GitHub handler that is setup for READMEs. Its here: https://github.com/omnivore-app/omnivore/blob/main/packages/content-handler/src/websites/github-handler.ts

Probably we can extend that one to handle issues also. (Also just noticed its an obvious copy and paste from the twitter one). 

The current GitHub handler looks for an article element, it looks like the issues data doesn't have one, so we basically need something like if (article) else if (`class="edit-comment-hide`) {} and then we can pull some of the content out of that comment block.
