### ISSUE TITLE
docker compose error on Rasberry PI 4

### ISSUE THREAD

**Issue by Erebus999** [omnivore-app/omnivore#2954]
Error:
 => ERROR [migrate  7/10] RUN apk --no-cache --virtual build-dependencies add postgresql uuidgen 
 Docker on Rasberry PI 4

 > [migrate  7/10] RUN apk --no-cache --virtual build-dependencies add postgresql uuidgen:
0.441 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/armv7/APKINDEX.tar.gz
5.447 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/armv7/APKINDEX.tar.gz
5.447 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
10.45 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)

No APKINDEX.tar.gz found https://dl-cdn.alpinelinux.org/alpine/v3.18/main/armv7/

**Comment by Erebus999** [comment]
i can load the APKINDEX.tar.gz in the Container and the dockerhost.

root@Docker:~/omnivore# docker run --rm -it alpine:3.18
/ # wget https://dl-cdn.alpinelinux.org/alpine/v3.18/community/armv7/APKINDEX.tar.gz
Connecting to dl-cdn.alpinelinux.org (151.101.2.132:443)
saving to 'APKINDEX.tar.gz'
APKINDEX.tar.gz      100% |*********************************************************************************************************************************************************************| 1332k  0:00:00 ETA
'APKINDEX.tar.gz' saved

**Comment by altbert** [comment]
The container causing the problem is named _migrate_

Notice that the Dockerfile in this project uses the image  `node:18.16-alpine`.

When trying to resolve using `docker run --rm -it --entrypoint sh node:18.16-alpine`
the file cannot be fetched

instead when using `docker run --rm -it --entrypoint sh --net=host node:18.16-alpine` (Only the `--net=host` option is added), there are no problems and the problem disappears.

I've tried adding the option `network_mode: "host"` to the docker-compose.yml file that configures the _migrate_ container, but the problem persists.

Any suggestions?

**Comment by Erebus999** [comment]
touch /etc/docker/daemon.json
nano /etc/docker/daemon.json

Insert:
{
  "dns": ["8.8.8.8"]
}

sudo service docker restart

**Comment by jacksonh** [comment]
I think we can just migrate this container (pun sort of intended) away from alpine and use debian. I'm trying to get it updated now
