### ISSUE TITLE
Read-random-article feature

### ISSUE THREAD

**Issue by igorrust** [omnivore-app/omnivore#3088]
I think it would be nice to have a "read random article" button, possibly for the inbox and/or archived folders. 
Motivation: Sometimes you just forget about what you've read before (or you are not sure with which unread-article to start :) )

**Comment by jacksonh** [comment]
Close eyes, scroll, tap :)

Yeah we do plan on adding this as a sort option. I _think_ you will want some ranking though

**Comment by masonc15** [comment]
+1 for this.  In the meantime, I'll use the blind scroll workaround 😄

**Comment by artjomsR** [comment]
I originally thought about having a random article button / feature as well. But as @jacksonh said, I think `random` sorting option would be a good starting point. Once the random sort is added, maybe some sort of "Go to next random article" button could be implemented - so you don't go back to the main screen and don't spoil what's next to read :)

**Comment by stevenrobertson** [comment]
> I think you will want some ranking though

I've used Instapaper's "Shuffle" sort a lot and really like it. A few observations:

- I used this this when I find a new author/newsletter/etc where I want to read a bunch of back issues, but reading them all straight through can be a slog. I'm using an e-ink device, so "close eyes, big scroll, click" doesn't work as well to get past these big blocks of articles.

- I don't think I need ranking for my use case. That said, Instapaper's version shuffles on device, and the on-device DB is limited (100 newest articles by default, up to 500 with a setting). So that acts as an implicit filter: only shuffle among the most recent X articles.

- Instapaper's shuffle is very unstable, it changes entirely any time the DB is modified. IMO it's a little disorienting. I'd prefer something like a sort key of `prng_hash(article_id + timestamp_trunc(now(), HOUR))`, as a compromise between stability and freshness.

**Comment by jacksonh** [comment]
> * Instapaper's shuffle is very unstable, it changes entirely any time the DB is modified. IMO it's a little disorienting. I'd prefer something like a sort key of `prng_hash(article_id + timestamp_trunc(now(), HOUR))`, as a compromise between stability and freshness.

Ah so you want to apply random on a filter basically. Like something along the lines of: `in:inbox subscription:"Some newsletter" sort:random` 

yeah doing it on device obviously simplifies a lot, pagination + random is kind of the issue.
