### ISSUE TITLE
Bug: There is no "import" button for Pocket integration on the web

### ISSUE THREAD

**Issue by saeedesmaili** [omnivore-app/omnivore#3256]
I have connected my Pocket account and since Omnivore doesn't sync the newly added items from Pocket automatically, I used to use the "Import" button in the [integrations page](https://omnivore.app/settings/integrations) every few days to manually sync my pocket account with omnivore. 

But the "import" button has been changed to "disconnect" recently, so I need to disconnect and connect and re-authorize my pocket account every few days to be able to keep these two synced.

**Comment by LightishRedd** [comment]
I thought I added this issue a few days ago but I can't seem to find it. I would switch over to using Omnivore completely, but it doesn't allow you to add labels as you save articles on Android. Pocket does.

When you "Disconnect" and reauthorize, does it resync with Pocket and download every article regardless of whether it's already in your app? I haven't tried to reconnect to Pocket because of that.

**Comment by saeedesmaili** [comment]
I'm using Inoreader ad my rss reader, and it has a built-in integration with pocket to easily save articles to read later while browsing the items in feed. So I can't stop using pocket for the time being. I wish omnivore automatically synced items from pocket every day (like what readwise reader does and automatically synces almost in real-time).
