### ISSUE TITLE
 ERROR [api builder 23/26] RUN yarn workspace @omnivore/api build 

### ISSUE THREAD

**Issue by dongjunke** [omnivore-app/omnivore#3315]
root@ddd:~/omnivore# docker compose up
[+] Building 388.7s (41/53)
 => CACHED [migrate  6/10] COPY /packages/db/package.json ./packages/db/package.json                                                   0.0s
 => CACHED [migrate  7/10] RUN apt-get update && apt-get install -y   postgresql   uuid-runtime                                        0.0s
 => CACHED [migrate  8/10] RUN yarn install                                                                                            0.0s
 => CACHED [migrate  9/10] ADD /packages/db ./packages/db                                                                              0.0s
 => CACHED [migrate 10/10] ADD /packages/db/setup.sh ./packages/db/setup.sh                                                            0.0s
 => [migrate] exporting to image                                                                                                       0.0s
 => => exporting layers                                                                                                                0.0s
 => => writing image sha256:00998b7667f7f10f30bc01d519044570dcd0d8d4ea201adeb06bad4d55b90dc9                                           0.0s
 => => naming to docker.io/library/omnivore-migrate                                                                                    0.0s
 => [api internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 2.16kB                                                                                                 0.0s
 => [api internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 156B                                                                                                      0.0s
 => [api internal] load build context                                                                                                  1.2s
 => => transferring context: 43.61MB                                                                                                   1.2s
 => CACHED [api runner  2/12] RUN apt-get update && apt-get install -y netcat-openbsd                                                  0.0s
 => CACHED [api runner  3/12] WORKDIR /app                                                                                             0.0s
 => CACHED [api builder  3/26] RUN apt-get update && apt-get install -y g++ make python3                                               0.0s
 => CACHED [api builder  4/26] COPY package.json .                                                                                     0.0s
 => CACHED [api builder  5/26] COPY yarn.lock .                                                                                        0.0s
 => CACHED [api builder  6/26] COPY tsconfig.json .                                                                                    0.0s
 => CACHED [api builder  7/26] COPY .prettierrc .                                                                                      0.0s
 => CACHED [api builder  8/26] COPY .eslintrc .                                                                                        0.0s
 => CACHED [api builder  9/26] COPY /packages/readabilityjs/package.json ./packages/readabilityjs/package.json                         0.0s
 => CACHED [api builder 10/26] COPY /packages/api/package.json ./packages/api/package.json                                             0.0s
 => CACHED [api builder 11/26] COPY /packages/text-to-speech/package.json ./packages/text-to-speech/package.json                       0.0s
 => CACHED [api builder 12/26] COPY /packages/content-handler/package.json ./packages/content-handler/package.json                     0.0s
 => CACHED [api builder 13/26] COPY /packages/liqe/package.json ./packages/liqe/package.json                                           0.0s
 => CACHED [api builder 14/26] RUN yarn install --pure-lockfile                                                                        0.0s
 => CACHED [api builder 15/26] ADD /packages/readabilityjs ./packages/readabilityjs                                                    0.0s
 => CACHED [api builder 16/26] ADD /packages/api ./packages/api                                                                        0.0s
 => CACHED [api builder 17/26] ADD /packages/text-to-speech ./packages/text-to-speech                                                  0.0s
 => CACHED [api builder 18/26] ADD /packages/content-handler ./packages/content-handler                                                0.0s
 => CACHED [api builder 19/26] ADD /packages/liqe ./packages/liqe                                                                      0.0s
 => CACHED [api builder 20/26] RUN yarn workspace @omnivore/text-to-speech-handler build                                               0.0s
 => CACHED [api builder 21/26] RUN yarn workspace @omnivore/content-handler build                                                      0.0s
 => CACHED [api builder 22/26] RUN yarn workspace @omnivore/liqe build                                                                 0.0s
 => ERROR [api builder 23/26] RUN yarn workspace @omnivore/api build                                                                  60.1s
^@

**Comment by jacksonh** [comment]
Can you provide the build error?

**Comment by thexmeta** [comment]
Hey, I am getting this error:

=> ERROR [api builder 26/29] RUN yarn workspace @omnivore/api build                                                               16.4s 
------
 > [api builder 26/29] RUN yarn workspace @omnivore/api build:
0.463 yarn workspace v1.22.19
0.742 yarn run v1.22.19
0.785 $ tsc
15.14
15.14 <--- Last few GCs --->
15.14
15.14 [40:0x6b0dcf0]    14042 ms: Mark-sweep (reduce) 978.0 (998.9) -> 977.9 (996.2) MB, 211.1 / 0.0 ms  (+ 3.5 ms in 2 steps since start
 of marking, biggest step 3.4 ms, walltime since start of marking 218 ms) (average mu = 0.318, current mu = 0.311) finalize [40:0x6b0dcf0
]    14045 ms: Scavenge 978.9 (996.2) -> 978.1 (999.2) MB, 1.7 / 0.0 ms  (average mu = 0.318, current mu = 0.311) allocation failure;    
15.14
15.14
15.14 <--- JS stacktrace --->
15.14
15.14 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
15.16  1: 0xb7a940 node::Abort() [/usr/local/bin/node]
15.16  2: 0xa8e823  [/usr/local/bin/node]
15.16  3: 0xd5c990 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
15.16  4: 0xd5cd37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
15.16  5: 0xf3a435  [/usr/local/bin/node]
15.17  6: 0xf3b338 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
15.17  7: 0xf4b843  [/usr/local/bin/node]
15.17  8: 0xf4c6b8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbac
kFlags) [/usr/local/bin/node]
15.17  9: 0xf4f885 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
15.17 10: 0xecd9df v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
15.17 11: 0x12ce115 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
15.18 12: 0x16fb6f9  [/usr/local/bin/node]
15.28 Aborted
15.58 error Command failed with exit code 134.
15.58 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16.03 error Command failed.
16.03 Exit code: 134
16.03 Command: /usr/local/bin/node
16.03 Arguments: /opt/yarn-v1.22.19/lib/cli.js build
16.03 Directory: /app/packages/api
16.03 Output:
16.03
16.04 info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn workspace @omnivore/api build" did not complete successfully: exit code: 134
