### ISSUE TITLE
Expose saved searches and subscriptions on a RSS feed

### ISSUE THREAD

**Issue by noghartt** [omnivore-app/omnivore#3575]
As a way to sync with another tools, like a RSS reader or anything like that, what about having an exposed RSS XML that let be consumed into another tool? Would be cool to have this possibility.

You could choose to do or don't publicly share it as a RSS feed also.

**Comment by jacksonh** [comment]
Yeah i like this idea, the only real issue is authentication. I think some tools do this by exposing an endpoint with a secret value in the URL, which isn't super secure but the only real option.

Does this mean you want to read in another reader, or using RSS to sync to places?

**Comment by noghartt** [comment]
> Does this mean you want to read in another reader, or using RSS to sync to places?

In case, I was thinking on my workflow, where I have some feeds and reading options that are handled directed by NetNewsWire. For Subscription, I was thinking to aggregate everything into just one place, for Subscription stuffs, it could redirect for the Omnivore's reading mode.

**Comment by candideu** [comment]
+1 for this!

Pocket [recently discontinued](https://support.mozilla.org/en-US/kb/can-i-subscribe-to-my-list-via-rss) their RSS feature, and I've been on the hunt for a replacement.

> Does this mean you want to read in another reader, or using RSS to sync to places?

For my use case: I use Fresh RSS to manage and sync all my feed subscriptions. My Android RSS reader of choice (Read You) supports Fresh RSS syncing, has a nice UI, and will soon offer text to speech. As such, I prefer using that over moving to Omnivore.

That said, I love using Omnivore to save articles for later on the go, and really wish I could access my entire list via a feed. This way, I can access the articles in my RSS reader instead of having to open a separate app or web page.

Related Issue: https://github.com/omnivore-app/omnivore/issues/409
