### ISSUE TITLE
Feature request: generate transcript of podcasts

### ISSUE THREAD

**Issue by italovieira** [omnivore-app/omnivore#3736]
This is the same idea and motivation of #2973 but for podcasts transcripts using maybe a third-party tool (?).

**Comment by jacksonh** [comment]
Hi @italovieira what tool do you normally use for podcasts? I'm trying to figure out the best way to fetch the data.

**Comment by italovieira** [comment]
> Hi @italovieira what tool do you normally use for podcasts? I'm trying to figure out the best way to fetch the data. 

I use Spotify, but I wouldn't mind using another app in order to have the transcript integrated.

**Comment by quinncomendant** [comment]
I use PocketCasts. When sharing an episode, it just shares a link like https://pca.st/kg2cui28 which opens a HTML page. 

It would be great if Omnivore could receive that, parse out the link to the mp3 file, transcribe the audio and format the response using OpenWhisper and an LLM, and save the result. If a podcast episode share page offers a transcript (Apple Podcasts?), just save that. It would be convenient if Apple's transcripts were publicly accessible, but if not using paid APIs might be affordable enough to offer to premium Omnivore subscribers.

**Comment by pinei** [comment]
Snipd is a podcast player that generates transcriptions using AI. The app allows to export highlights to markdown or 3rd party readers, but there is no option to export the transcriptions.  Such a restriction is related to copyright.

**Comment by ufuksfk** [comment]
I am actively using Snipd and also Matter for that use case. As sidenote, I am so podcast addict that I am listening to podcast with 2 hours per day frequency for more than 3 years.

So I really loved omnivore app and the idea behind it. I am now trying to understand how can I help you to make it real. I strongly believe it might be very good way to seperate free and paid users.

For the copyright thing, there is also no user experience of listening to the audiobook while you can also follow the text. Another thing is [matter](https://getmatter.com/), [snipd](https://www.snipd.com/), readwise all have "tap to headphones to highlight" option, I failed to find that convenience in any audiobook app.

So, I am not a lawyer, but I believe transcribing a podcast versus transcribing a book is totally different problems. For the podcast part, there is also something called [podcast 2.0](https://podcasting2.org/apps). Last time I checked, they have a tag for transcript.
A couple of links for podcast 2.0:
https://podcastindex.org/
https://podcastindex.org/podcast/920666 That podcast has transcripts as srt for example.
Actually, having a transcript for a podcast is also useful for podcast publishers. [Freakonomics ](https://freakonomics.com/podcast/the-language-of-the-universe/)is doing that for very long time. But I still need to use snipd or matter to get transcription and highlight important parts while listening. So, normally solutions seems to have new RSS format for podcast so that creators can add their transcripts with timetag.
