### ISSUE TITLE
iOS: App Crashes on iOS 18 Beta

### ISSUE THREAD

**Issue by jxstxn1** [omnivore-app/omnivore#4062]
When you try to Click on an Article the App Crashes.

iOS Version: iOS 18.0 (22A5282m)
Omnivore Version: 1.45

https://github.com/omnivore-app/omnivore/assets/29661951/bb62eb39-9add-46b9-b62a-79fefa3d3f30

**Comment by f6cm** [comment]
I can confirm the same behavior. It also crashes when you add a new feed.

**Comment by Joeb454** [comment]
I have the same issue, even on the just-released Dev Beta 2.

I did try and pull the code down though, and running this in an iOS 18 simulator it works exactly as you'd expect, so this (unfortunately) might be a case of compiling against an iOS 18 SDK, rather than a code fix.

I could be wrong, but there was no crash I could capture from Xcode in that scenario.

**Comment by Joeb454** [comment]
In the interest of keeping this up to date, I can confirm that this still happens on developer beta 3.

As above though, compiling against the iOS 18 SDK seems to work as expected.

**Comment by Bleushift** [comment]
This is still happening on iOS Beta 3 update - both iPad and Phone. Mac seems fine on latest Mac OS update.

App opens but as soon as I click an article it crashes.

**Comment by saurerzipfel** [comment]
Fixed for me!
