### ISSUE TITLE
Allow setting labels at time of save

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#648]
We should be able to set tags from the share extension on iOS and the share popup in the browser extension.

<img width="364" alt="Screen Shot 2022-06-15 at 16 39 52" src="https://user-images.githubusercontent.com/75189/173959937-622c56ff-867e-4fdc-b84f-f9e61259a2ac.png">

Figma: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=2957%3A71228

**Comment by xplosionmind** [comment]
The ”Read now” and “Skip” buttons are fairly wide… what about shrinking them by using icons only, and add other buttons? I would suggest:
- a ✅ or 🗂 to Archive
- a ⭐️ to mark as favorite
- a 🗑 to delete (in case the article was added by mistake)
- (possibly, since the space left is coming short) a ✏️ to edit metadata (see #900)

**Comment by jacksonh** [comment]
I think we have all this functionality, minus favorites now. We will come back to the extension in a few weeks after cleaning up some other design
