### ISSUE TITLE
Image proxy fails for image on CBS news site

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#72]
Original URL: https://www.cbsnews.com/amp/news/brigham-and-womens-hospital-boston-refusing-heart-transplant-man-wont-get-vaccinated/ 

My saved copy: https://omnivore.app/jacksonh/hospital-refusing-heart-transplant-for-man-who-won-t-get-vaccina-17f03c89f06 

Note the top image is not correctly fetched by the image proxy.

**Comment by odebroqueville** [comment]
I don't think that the image proxy is failing here. I'm not sure that the image tag is being identified as such because it's weird: <amp-img> within a <span> block:

<img width="763" alt="Screenshot 2024-01-17 at 09 42 04" src="https://github.com/omnivore-app/omnivore/assets/4818315/1bd77e80-52fd-4134-ba96-afa717877d86">

Here is the result feeding the correct img src to imageproxy (no issue):

<img width="1538" alt="Screenshot 2024-01-17 at 09 36 14" src="https://github.com/omnivore-app/omnivore/assets/4818315/cb6589c6-a65a-4bd0-8e65-30c311ee7206">
